### PR TITLE
Modified Count_String.Py file in String folder using re module(With Comments)

### PR DESCRIPTION
**Pull request by Shubhamsharma09**

### CODE REVIEW

**Review by sahilrider — CHANGES_REQUESTED** [review]
This is a good use of re module, but before merging i want that you also add comments about how compile and findall are working.

**Comment by Shubhamsharma09** [comment]
ok, no problem :)

**Review by sahilrider — APPROVED** [review]

**Comment by sahilrider** [comment]
Good work @Shubhamsharma09 #10

**Comment by Shubhamsharma09** [comment]
Thanks, looking forward to make some more changes.

**Pull request merged**
